# Indicator Runner
Run a selection of metrics based on config file.

In [1]:
import pandas as pd
from pathlib import Path
import matplotlib.pyplot as plt
import seaborn as sns
import logging

# Set the root logger's level to INFO
logging.getLogger().setLevel(logging.INFO)

In [2]:
# autoreload changes from local files
%load_ext autoreload
%autoreload 2

# pandas show full output
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 200)

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [3]:
from indicatorenplan_limburg.configs.settings import load_yaml_config
from indicatorenplan_limburg.system.runner import IndicatorRunner

## Config
First we load and inspect the config. This contains all settings to be used for the system, including paths, runner settings and indicator-specific configuration. 

We separate these into a separate configuration file in YAML format to ensure that people without python knowledge can easily see and adapt configuration settings without delving into the codebase.

In [4]:
config = load_yaml_config()
config

{'paths': {'data': '~/data/Indicatorenplan-limburg'},
 'runner': {'years': [2023, 2027],
  'include_categories': ['toekomstbestendige_economie'],
  'exclude_indicators': [],
  'retain_input': True,
  'retain_output': True,
  'log_level': 'DEBUG'},
 'indicators': {'toekomstbestendige_economie': {'mo7i': {'name': 'MO_7i Vestigingen per grootteklasse per sector',
    'grootteklasse': "('0_9', '10_49', '50_99', '100_249', '250_9999')",
    'metadata': ['onderwerpen',
     'dim_sbi',
     'dim_grootteklasse',
     'dim_geoitem']},
   'd21a': {'name': 'D_21a Aantal MKB bedrijven in Limburg met proces- en productinnovaties',
    'metadata': ['onderwerpen']},
   'd21b': {'name': 'D_21b Aantal MKB bedrijven in innovatieve samenwerkingsverbanden',
    'metadata': ['onderwerpen']},
   'd23a': {'name': 'D_23a Aantal startende innovatieve bedrijven',
    'metadata': ['onderwerpen']}}}}

## Runner

Let's first inspect which indicators have been implemented so far by consulting the registry.

In [5]:
# first we need to discover all indicators in the repository
from indicatorenplan_limburg.system.registry import IndicatorRegistry
IndicatorRegistry.discover_indicators()
# then we can load the registry
registry = IndicatorRegistry.get_registry()
registry

[2025-06-19 10:53:23] [INFO] [indicatorenplan_limburg.system.registry]: Discovered indicators: ['mo11a', 'd21a', 'd21b', 'd23a', 'mo7i']

{'mo11a': indicatorenplan_limburg.indicatoren.leefbare_steden_en_dorpen.mo11a.IndicatorMO11A,
 'd21a': indicatorenplan_limburg.indicatoren.toekomstbestendige_economie.d21a.IndicatorD21a,
 'd21b': indicatorenplan_limburg.indicatoren.toekomstbestendige_economie.d21b.IndicatorD21b,
 'd23a': indicatorenplan_limburg.indicatoren.toekomstbestendige_economie.d23a.IndicatorD23a,
 'mo7i': indicatorenplan_limburg.indicatoren.toekomstbestendige_economie.mo7i.IndicatorMO7i}

In [6]:
# IndicatorRegistry._fail_load

In [8]:
indicator_runner = IndicatorRunner()
indicator_runner.run()

[2025-06-19 10:56:22] [INFO] [IndicatorRunner]: Initializing IndicatorRunner with config.
[2025-06-19 10:56:22] [INFO] [indicatorenplan_limburg.system.registry]: Discovered indicators: ['mo11a', 'd21a', 'd21b', 'd23a', 'mo7i']
[2025-06-19 10:56:22] [WARNING] [IndicatorRunner]: Retaining input or output data may significantly slow down the process. Consider disabling these options in the config file.
[2025-06-19 10:56:22] [INFO] [IndicatorRunner]: Initializing indicators that are included in run: ['d21a', 'd21b', 'd23a', 'mo7i']
[2025-06-19 10:56:22] [INFO] [IndicatorD21a]: Initializing IndicatorD21a with config: {'name': 'D_21a Aantal MKB bedrijven in Limburg met proces- en productinnovaties', 'metadata': ['onderwerpen']}
[2025-06-19 10:56:22] [INFO] [IndicatorD21b]: Initializing IndicatorD21b with config: {'name': 'D_21b Aantal MKB bedrijven in innovatieve samenwerkingsverbanden', 'metadata': ['onderwerpen']}
[2025-06-19 10:56:22] [INFO] [IndicatorD23a]: Initializing IndicatorD23a with config: {'name': 'D_23a Aantal startende innovatieve bedrijven', 'metadata': ['onderwerpen']}
[2025-06-19 10:56:22] [INFO] [IndicatorMO7i]: Initializing IndicatorMO7i with config: {'name': 'MO_7i Vestigingen per grootteklasse per sector', 'grootteklasse': "('0_9', '10_49', '50_99', '100_249', '250_9999')", 'metadata': ['onderwerpen', 'dim_sbi', 'dim_grootteklasse', 'dim_geoitem']}
[2025-06-19 10:56:22] [INFO] [IndicatorRunner]: Running all indicators...
[2025-06-19 10:56:22] [INFO] [IndicatorRunner]: Running indicator: d21a
[2025-06-19 10:56:22] [INFO] [IndicatorD21a]: Loading data from ~/data/Indicatorenplan-limburg/toekomstbestendige_economie/d21a/input
[2025-06-19 10:56:25] [INFO] [IndicatorD21a]: Saved results to /Users/dknoors/data/Indicatorenplan-limburg/toekomstbestendige_economie/d21a/output/D_21a Aantal MKB bedrijven in Limburg met proces- en productinnovaties.xlsx
[2025-06-19 10:56:25] [INFO] [IndicatorD21a]: Finished processing IndicatorD21a - output saved to ~/data/Indicatorenplan-limburg/toekomstbestendige_economie/d21a/output
[2025-06-19 10:56:25] [INFO] [IndicatorRunner]: Running indicator: d21b
[2025-06-19 10:56:25] [INFO] [IndicatorD21b]: Loading data from ~/data/Indicatorenplan-limburg/toekomstbestendige_economie/d21b/input
[2025-06-19 10:56:28] [INFO] [IndicatorD21b]: Saved results to /Users/dknoors/data/Indicatorenplan-limburg/toekomstbestendige_economie/d21b/output/D_21b Aantal MKB bedrijven in innovatieve samenwerkingsverbanden.xlsx
[2025-06-19 10:56:28] [INFO] [IndicatorD21b]: Finished processing IndicatorD21b - output saved to ~/data/Indicatorenplan-limburg/toekomstbestendige_economie/d21b/output
[2025-06-19 10:56:28] [INFO] [IndicatorRunner]: Running indicator: d23a
[2025-06-19 10:56:28] [INFO] [IndicatorD23a]: Loading data from ~/data/Indicatorenplan-limburg/toekomstbestendige_economie/d23a/input
/Users/dknoors/Library/Caches/pypoetry/virtualenvs/indicatorenplan-limburg-8JyB5Tk6-py3.12/lib/python3.12/site-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
[2025-06-19 10:56:28] [INFO] [IndicatorD23a]: Saved results to /Users/dknoors/data/Indicatorenplan-limburg/toekomstbestendige_economie/d23a/output/D_23a Aantal startende innovatieve bedrijven.xlsx
[2025-06-19 10:56:28] [INFO] [IndicatorD23a]: Finished processing IndicatorD23a - output saved to ~/data/Indicatorenplan-limburg/toekomstbestendige_economie/d23a/output
[2025-06-19 10:56:28] [INFO] [IndicatorRunner]: Running indicator: mo7i
[2025-06-19 10:56:28] [INFO] [IndicatorMO7i]: Loading data from ~/data/Indicatorenplan-limburg/toekomstbestendige_economie/mo7i/input
[2025-06-19 10:57:48] [INFO] [IndicatorMO7i]: MO7i - Processing data for vrl2023
[2025-06-19 10:57:48] [INFO] [IndicatorMO7i]: MO7i - Processing data for vrl2024
[2025-06-19 10:57:48] [INFO] [IndicatorMO7i]: Saved results to /Users/dknoors/data/Indicatorenplan-limburg/toekomstbestendige_economie/mo7i/output/MO_7i Vestigingen per grootteklasse per sector.xlsx
[2025-06-19 10:57:48] [INFO] [IndicatorMO7i]: Finished processing IndicatorMO7i - output saved to ~/data/Indicatorenplan-limburg/toekomstbestendige_economie/mo7i/output

In [11]:
indicator_runner.indicators['d23a'].output_data_

    jaar totaal_campus totaal_limburg
1   2012            18           8011
2   2013            14           8142
3   2014            12           8151
4   2015            13           8119
5   2016            26           8224
6   2017            40           8118
7   2018            43           8461
8   2019            37           9340
9   2020            38          10105
10  2021            23          10807
11  2022            22          10844
12  2023            39          11746

In [12]:
indicator_runner.indicators['mo7i'].input_data_

{'vrl2023':         PEILDATUM                   SBI_1_NAAM  WP_FPU_TOTAAL      COROP_NAAM
 0      2023-01-01                    Industrie            177   Noord-Limburg
 1      2023-01-01                    Industrie            110   Noord-Limburg
 2      2023-01-01                    Industrie             25   Noord-Limburg
 3      2023-01-01                    Industrie             82   Noord-Limburg
 4      2023-01-01                    Industrie             58   Noord-Limburg
 ...           ...                          ...            ...             ...
 113103 2023-01-01            Vervoer en opslag              1   Noord-Limburg
 113104 2023-01-01      Overige dienstverlening              5    Zuid-Limburg
 113105 2023-01-01                    Industrie            326   Noord-Limburg
 113106 2023-01-01            Vervoer en opslag            200  Midden-Limburg
 113107 2023-01-01  Cultuur, sport en recreatie              1    Zuid-Limburg

 [113108 rows x 4 columns],
 'vrl2024':        PEILDATUM                                    SBI_1_NAAM  WP_FPU_TOTAAL  \
 0       1-1-2024                                     Industrie            168
 1       1-1-2024                                     Industrie            118
 2       1-1-2024                                     Industrie             25
 3       1-1-2024                                     Industrie             81
 4       1-1-2024                                     Industrie             58
 ...          ...                                           ...            ...
 117780  1-1-2024  Groot- en detailhandel; reparatie van auto’s              1
 117781  1-1-2024                  Gezondheids- en welzijnszorg              1
 117782  1-1-2024  Groot- en detailhandel; reparatie van auto’s              2
 117783  1-1-2024                       Overige dienstverlening              1
 117784  1-1-2024                       Overige dienstverlening              1

            COROP_NAAM
 0       Noord-Limburg
 1       Noord-Limburg
 2       Noord-Limburg
 3       Noord-Limburg
 4       Noord-Limburg
 ...               ...
 117780  Noord-Limburg
 117781   Zuid-Limburg
 117782   Zuid-Limburg
 117783  Noord-Limburg
 117784   Zuid-Limburg

 [117785 rows x 4 columns]}

## Archive

In [ ]:
from indicatorenplan_limburg.indicatoren.toekomstbestendige_economie.mo_7i import IndicatorMO7i
mo7i = IndicatorMO7i(retain_input=True, retain_output=True)

In [ ]:
mo7i.config

{'name': 'MO_7i Vestigingen per grootteklasse per sector',
 'grootteklasse': "('0_9', '10_49', '50_99', '100_249', '250_9999')",
 'metadata': ['onderwerpen', 'dim_sbi', 'dim_grootteklasse', 'dim_geoitem']}

In [ ]:
mo7i.category

'toekomstbestendige_economie'

In [ ]:
mo7i.code

'mo7i'

In [ ]:
path = Path('~/data/indicatorenplan-limburg/toekomstbestendige_economie/mo7i/input/').expanduser()
# [f for f in path.glob(f"*.x")]
import os 
os.listdir(path)
# # show all files in path
# path = Path('~/data/Indicatorenplan-limburg/toekomstbestendige_economie/mo7i/input/')

['vrl2023.xlsx', 'vrl2024.xlsx']

In [ ]:
df = pd.read_excel('~/data/Indicatorenplan-limburg/toekomstbestendige_economie/mo7i/input/vrl2023.xlsx', engine='openpyxl')

In [ ]:
df.head()

,PEILDATUM,ID_BAG_ADRES,ID_BAG_VBO,ID_BAG_PAND,STRAATNAAM,HUISNR,HUISLTR,HUISNR_TOEV,POSTCODE,WOONPLAATS,CORR_STRAAT,CORR_HUISNR,CORR_HUISLTR,CORR_TOEV,CORR_POSTCODE,CORR_WOONPLAATS,X,Y,XY_KWAL,VESTNR,NAAM,CORR_NAAM,KVK_DOSNR,KVK_VESTNR,TELNR,FAXNR,SBI_5_CODE,SBI_5_NAAM,SBI_4_CODE,SBI_4_NAAM,SBI_3_CODE,SBI_3_NAAM,SBI_2_CODE,SBI_2_NAAM,SBI_1_CODE,SBI_1_NAAM,DATUM_START,VEST_SOORT,WP_F_MAN,WP_F_VROUW,WP_F_TOTAAL,WP_P_MAN,WP_P_VROUW,WP_P_TOTAAL,WP_FP_TOTAAL,WP_UF_MAN,WP_UF_VROUW,WP_UF_TOTAAL,WP_UP_MAN,WP_UP_VROUW,WP_UP_TOTAAL,WP_U_TOTAAL,WP_FPU_TOTAAL,GRKL_FPU,GRKL_FP,GRKL_F,BUURT_CODE,BUURT_NAAM,WOONMILIEU,WIJK_CODE,WIJK_NAAM,GEM_CODE,GEM_NAAM,WOONREGIO_NAAM,WGR_NAAM,COROP_NAAM,PROVINCIE,STADSREGIO,BBG_NAAM,BBG_FUNCTIE,PCM_PLANCODE,PCM_PLANNAAM,TERREIN_CODE,TERREIN_NAAM,TERREIN_VESTM_1,TERREIN_VESTM_2
0,2023-01-01,0983200000158406,0983010000158391,9.831000e+14,Oude Venloseweg,84,,,5941HG,Velden,Oude Venloseweg,84,,,5941HG,Velden,208895.015625,379473.625,Via BAG Verblijfsobject,111-060-541,Okechamp B.V.,Okechamp B.V.,12019548,000018499635,077-4728100,077-4728063,1039,Verwerking van groente en fruit (niet tot sap ...,1039,Verwerking van groente en fruit (niet tot sap ...,103,"Verwerking van aardappels, groente en fruit",10,Vervaardiging van voedingsmiddelen,C,Industrie,1-5-1985 00:00:00,1,120,18,138,0,0,0,138,24,15,39,0,0,0,39,177,8,8,8,9834105,Hasselt en Het Vorst,Landelijk,WK098341,Velden,GM0983,Venlo,Noord-Limburg,Noord-Limburg,Noord-Limburg,Limburg,NaN,Velden,Werken,NaN,NaN,200218.0,Lutece (Velden),Solitair bedrijf,Overig terrein (BT)
1,2023-01-01,0983200000154481,0983010000154481,9.831000e+14,Spikweien,50,,,5943AD,Lomm,Spikweien,48,,,5943AD,Lomm,210025.000000,384490.000,Via BAG Verblijfsobject,111-060-566,Aviko Lomm,Aviko Lomm,08027672,000016075994,0575-458200,077-4737331,1031,Vervaardiging van aardappelproducten,1031,Vervaardiging van aardappelproducten,103,"Verwerking van aardappels, groente en fruit",10,Vervaardiging van voedingsmiddelen,C,Industrie,1-5-1985 00:00:00,23,101,6,107,1,0,1,108,2,0,2,0,0,0,2,110,8,8,8,9834302,Spikweien,Landelijk,WK098343,Lomm,GM0983,Venlo,Noord-Limburg,Noord-Limburg,Noord-Limburg,Limburg,NaN,Lomm,Werken,NaN,NaN,203491.0,Spikweien,Bedrijventerrein,Bedrijventerrein landelijk gebied
2,2023-01-01,0983200000154482,0983010000154482,9.831000e+14,Spikweien,56,,,5943AD,Lomm,Spikweien,56,,,5943AD,Lomm,209905.000000,384522.000,Via BAG Verblijfsobject,111-060-598,L. van den Hombergh Lomm B.V.,L. van den Hombergh Lomm B.V.,12045751,000017419859,077-4731450,077-4731278,1624,Vervaardiging van houten emballage,1624,Vervaardiging van houten emballage,162,"Vervaardiging van artikelen van hout, kurk, ri...",16,Primaire houtbewerking en vervaardiging van ar...,C,Industrie,1-5-1985 00:00:00,3,25,0,25,0,0,0,25,0,0,0,0,0,0,0,25,6,6,6,9834302,Spikweien,Landelijk,WK098343,Lomm,GM0983,Venlo,Noord-Limburg,Noord-Limburg,Noord-Limburg,Limburg,NaN,Lomm,Werken,NaN,NaN,203491.0,Spikweien,Bedrijventerrein,Bedrijventerrein landelijk gebied
3,2023-01-01,0983200000154487,0983010000154487,9.831000e+14,Spikweien,70,,,5943AD,Lomm,Spikweien,70,,,5943AD,Lomm,209837.000000,384546.000,Via BAG Verblijfsobject,111-060-613,Ami B.V.,Ami B.V.,12009834,000019128088,077-4737475,077-4737479,2572,Vervaardiging van hang- en sluitwerk,2572,Vervaardiging van hang- en sluitwerk,257,"Vervaardiging v. scharen, messen, bestek, hang...",25,Vervaardiging van prod. van metaal (geen machi...,C,Industrie,1-5-1985 00:00:00,3,51,22,73,0,2,2,75,5,2,7,0,0,0,7,82,7,7,7,9834302,Spikweien,Landelijk,WK098343,Lomm,GM0983,Venlo,Noord-Limburg,Noord-Limburg,Noord-Limburg,Limburg,NaN,Lomm,Werken,NaN,NaN,203491.0,Spikweien,Bedrijventerrein,Bedrijventerrein landelijk gebied
4,2023-01-01,0983200000154469,0983010000154469,9.831000e+14,Spikweien,27,,,5943AC,Lomm,Spikweien,27,,,5943AC,Lomm,210022.000000,384450.000,Via BAG Verblijfsobject,111-060-638,Aalberts Surface Technologies Venlo B.V.,Aalberts Surface Technologies Venlo B.V.,12010784,000015848868,077-3081333,077-4732409,2561,Oppervlaktebehandeling en bekleding van metaal,2561,Oppervlaktebehandeling en bekleding van metaal,256,Oppervlaktebehandeling en bekleding van metaal;,25,Vervaardiging van prod. van metaal (geen machi...,C,Industrie,1-5-1985 00:00:00,3,39,14,53,0,0,0,53,3,2,5,0,0,0,5,58,7,7,7,9834302,Spikweien,Landelijk,WK098343,Lomm,GM0983,Venlo,Noord-Limburg,Noord-Limburg,Noord-Limburg,Limburg,NaN,Lomm,Werken,NaN,NaN,203491.0,Spikweien,Bedrijventerrein,Bedrijventerrein landelijk gebied